apiVersion: v1
kind: Service
metadata:
  name: js-single-node
spec:
  selector:
    app.kubernetes.io/instance: js-single-node
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
