apiVersion: ps.percona.com/v1alpha1
kind: PerconaServerMySQL
metadata:
  name: cluster1
  finalizers:
    - percona.com/delete-mysql-pods-in-order
spec:
  unsafeFlags:
    mysqlSize: true
    orchestrator: false
    orchestratorSize: false
    proxy: true
    proxySize: false
  crVersion: 0.8.0
  secretsName: cluster1-secrets
  sslSecretName: cluster1-ssl
  updateStrategy: SmartUpdate
  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: disabled
  mysql:
    clusterType: async
    autoRecovery: true
    image: flyio/percona-server-mysql-operator:fks-11
    imagePullPolicy: Always
    size: 1
    resources:
      requests:
        memory: 1G
      limits:
        memory: 2G
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2G
  toolkit:
    image: flyio/percona-server-mysql-operator:fks-11
    imagePullPolicy: Always

  backup:
    enabled: false
    image: flyio/percona-server-mysql-operator:fks-11

  proxy:
    haproxy:
      enabled: false
      size: 3
      image: flyio/percona-server-mysql-operator:fks-11
      imagePullPolicy: Always
      resources:
        requests:
          memory: 1G
          cpu: 600m
    router:
      enabled: false
      image: flyio/percona-server-mysql-operator:fks-11
      imagePullPolicy: Always

  orchestrator:
    enabled: true
    image: flyio/percona-server-mysql-operator:fks-11
    imagePullPolicy: Always
    size: 3
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        memory: 128M
      limits:
        memory: 256M

    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1G

  pmm:
    enabled: false
    image: percona/pmm-client:2.41.2
    imagePullPolicy: Always
    resources:
      requests:
        memory: 150M
        cpu: 300m
