apiVersion: ps.percona.com/v1alpha1
kind: PerconaServerMySQL
metadata:
  name: async-multinode
  finalizers:
    - percona.com/delete-mysql-pods-in-order
spec:
  # Two-node install is considered unsafe
  unsafeFlags:
    mysqlSize: true
    orchestratorSize: true
  crVersion: 0.8.0
  secretsName: cluster1-secrets
  sslSecretName: cluster1-ssl
  updateStrategy: RollingUpdate
  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: disabled
  mysql:
    clusterType: async
    autoRecovery: true
    image: flyio/percona-server-mysql-operator:ps-mysql
    imagePullPolicy: Always
    size: 2
    resources:
      requests:
        memory: 1G
      limits:
        memory: 2G
    affinity:
      antiAffinityTopologyKey: none
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2G
  toolkit:
    image: flyio/percona-server-mysql-operator:ps-mysql
    imagePullPolicy: Always
    resources:
      requests:
        memory: 1G
      limits:
        memory: 2G

  backup:
    enabled: true
    image: flyio/percona-server-mysql-operator:ps-mysql
    resources:
      requests:
        memory: 1G
      limits:
        memory: 2G
    storages:
      tigris:
        type: s3
        s3:
          bucket: js-mysql-backup
          region: auto
          credentialsSecret: s3-credentials
          endpointUrl: https://fly.storage.tigris.dev

  orchestrator:
    enabled: true
    image: flyio/percona-server-mysql-operator:ps-orchestrator
    imagePullPolicy: Always
    size: 1
    affinity:
      antiAffinityTopologyKey: none
    resources:
      requests:
        memory: 1G
      limits:
        memory: 2G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1G

  proxy:
    haproxy:
      enabled: true
      size: 1
      image: flyio/percona-server-mysql-operator:ps-haproxy
      imagePullPolicy: Always
      resources:
        requests:
          memory: 1G
      affinity:
        antiAffinityTopologyKey: none
