apiVersion: ps.percona.com/v1alpha1
kind: PerconaServerMySQL
metadata:
  name: single-node
  finalizers:
    - percona.com/delete-mysql-pods-in-order
spec:
  # Single node installs need these settings, since orchestrator and haproxy are required for async replication
  unsafeFlags:
    mysqlSize: true
    orchestrator: true
    proxy: true
  crVersion: 0.8.0
  secretsName: cluster1-secrets
  sslSecretName: cluster1-ssl
  updateStrategy: RollingUpdate
  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: disabled
  mysql:
    clusterType: async
    autoRecovery: true
    image: flyio/percona-server-mysql-operator:ps-mysql
    imagePullPolicy: Always
    size: 1
    resources:
      requests:
        memory: 1G
      limits:
        memory: 2G
    affinity:
      antiAffinityTopologyKey: none
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2G
  toolkit:
    image: flyio/percona-server-mysql-operator:ps-mysql
    imagePullPolicy: Always
    resources:
      requests:
        memory: 1G
      limits:
        memory: 2G

  backup:
    enabled: true
    image: flyio/percona-server-mysql-operator:ps-mysql
    resources:
      requests:
        memory: 1G
      limits:
        memory: 2G
    storages:
      tigris:
        type: s3
        s3:
          bucket: js-mysql-backup
          region: auto
          credentialsSecret: s3-credentials
          endpointUrl: https://fly.storage.tigris.dev
