# Via `fly storage create` with base64 encoded values
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: base64_encoded_value
  AWS_SECRET_ACCESS_KEY: base64_encoded_value
